name: SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  sonarqube-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      - name: SonarQube Scan
        run: |
          mvn sonar:sonar \
            -Dsonar.host.url=http://localhost:9000
            -Dsonar.login=${{squ_d49c14a014a48d06c60328c88ca2a85b4c9f7a82}}
